version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: process.env.DB_NAME
      MYSQL_USER: process.env.DB_USER
      MYSQL_PASSWORD: process.env.DB_PASSWORD
      MYSQL_ROOT_PASSWORD: process.env.DB_ROOT_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run dev

volumes:
  db_data:
